service: aws-node-json-api-monkko

provider:
  name: aws
  runtime: nodejs8.10

functions:

  login:
    handler: userHandler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  registerUser:
    handler: userHandler.registerUser
    events:
      - http:
          path: register
          method: post
          cors: true

  updateUser:
    handler: userHandler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  deleteUser:
    handler: userHandler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  user:
    handler: userHandler.user
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  getAll:
    handler: musicHandler.getAll
    events:
      - http:
          path: getAll
          method: get
          cors: true

  tracks:
    handler: musicHandler.getTracks
    events:
      - http:
          path: tracks
          method: get
          cors: true



  album:
    handler: musicHandler.album
    events:
      - http:
          path: albums/{id}
          method: get
          cors: true
  artist:
    handler: musicHandler.artist
    events:
      - http:
          path: artists/{id}
          method: get
          cors: true
  genre:
    handler: musicHandler.genre
    events:
      - http:
          path: genres/{id}
          method: get
          cors: true
  mediaType:
    handler: musicHandler.mediaType
    events:
      - http:
          path: mediaTypes/{id}
          method: get
          cors: true


  editTrack:
    handler: musicHandler.editTrack
    events:
      - http:
          path: tracks/{id}
          method: put
          cors: true

  addTrack:
    handler: musicHandler.addTrack
    events:
      - http:
          path: tracks
          method: post
          cors: true

  removeTrack:
    handler: musicHandler.removeTrack
    events:
      - http:
          path: tracks/{id}
          method: delete
          cors: true

  spotifySearch:
    handler: spotifyHandler.search
    events:
      - http:
          path: spotify/search
          method: post
          cors: true
          

  mysql:
    handler: mysqlHandler.mysql
    events:
      - http:
          path: mysql
          method: get
          cors: true

plugins:
  - serverless-offline