service: aws-node-rest-api-monkko

provider:
  name: aws
  runtime: nodejs8.10

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: register
          method: post
          cors: true

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  user:
    handler: handler.user
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  getAll:
    handler: musicHandler.getAll
    events:
      - http:
          path: getAll
          method: get
          cors: true

  tracks:
    handler: musicHandler.getTracks
    events:
      - http:
          path: tracks
          method: get
          cors: true

  spotifyAuthentication:
    handler: spotifyHandler.authenticate
    events:
      - http:
          path: spotifyAuthentication
          method: get
          cors: true
plugins:
  - serverless-offline